<a href="https://colab.research.google.com/github/MNTech955/100-days-of-machine-learning/blob/main/handling_date_time_variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
date = pd.read_csv('sample_data/orders.csv')
time = pd.read_csv('sample_data/messages.csv')
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [3]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [4]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [5]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

Working with Dates

In [6]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1. Extract year

In [7]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
56  2018-11-12        3667       13      20       2018
183 2019-02-08        4785       14       4       2019
424 2019-10-12         637       26       1       2019
933 2019-07-04        7138       28       3       2019
628 2019-08-03        5823       27       1       2019

2. Extract Month

In [8]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

In [9]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

Extract Days

In [10]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [11]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [12]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [13]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

Extract week of the year

In [19]:
# Ensure that the 'date' column is in datetime format
date['date'] = pd.to_datetime(date['date'])

# Now extract the week of the year using the isocalendar() method
date['date_week'] = date['date'].apply(lambda x: x.isocalendar()[1])

# Dropping unnecessary columns
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

Extract Quarter

In [21]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

In [23]:
# date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2):

# date['quarter']: This accesses the quarter column in the date DataFrame.
# isin([1,2]): This checks if the value in the quarter column is either 1 or 2.
#  It returns a boolean result (True if the value is in [1, 2], otherwise False).
# np.where(condition, value_if_true, value_if_false): This is a conditional function from numpy.
# If the condition is True (i.e., if the value in quarter is 1 or 2),
# then 1 is assigned to the corresponding row in the new semester column.
# If the condition is False (i.e., if the value in quarter is neither 1 nor 2), then 2 is assigned to the semester column.
# Result: The semester column will be filled with 1 for records where quarter is 1 or 2, and 2 for records where quarter is 3 or 4.

# Example:

# If a row has quarter = 1, the new column semester will have 1.
# If a row has quarter = 3, the new column semester will have 2.
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter,date_week,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,50,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,33,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,43,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,33,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

Extract Time elapsed between dates

In [24]:
import datetime
#The datetime.today() method from the datetime class returns the current local date and time
#  (i.e., the "now" moment when the code is run).
today = datetime.datetime.today()

today

datetime.datetime(2026, 5, 7, 10, 36, 45, 898879)

In [25]:
#Finally, it calculates the difference between the current date (today) and the date from a column (date['date']) in a DataFrame,
# yielding a time difference (timedelta).
today - date['date']

0     2340 days 10:36:45.898879
1     2822 days 10:36:45.898879
2     2753 days 10:36:45.898879
3     2455 days 10:36:45.898879
4     2678 days 10:36:45.898879
                 ...
995   2768 days 10:36:45.898879
996   2709 days 10:36:45.898879
997   2557 days 10:36:45.898879
998   2622 days 10:36:45.898879
999   2396 days 10:36:45.898879
Name: date, Length: 1000, dtype: timedelta64[ns]

In [26]:
(today - date['date']).dt.days

0      2340
1      2822
2      2753
3      2455
4      2678
       ...
995    2768
996    2709
997    2557
998    2622
999    2396
Name: date, Length: 1000, dtype: int64

In [28]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [29]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [30]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

Extract Time part

In [31]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

Time difference

In [32]:
today - time['date']

0     4526 days 09:46:45.898879
1     4390 days 10:56:45.898879
2     4876 days 10:15:45.898879
3     4178 days 10:05:45.898879
4     4575 days 11:25:45.898879
                 ...
995   5165 days 09:46:45.898879
996   4486 days 11:22:45.898879
997   4951 days 10:59:45.898879
998   5067 days 11:02:45.898879
999   4339 days 11:11:45.898879
Name: date, Length: 1000, dtype: timedelta64[ns]